package com.doctorfast.cs.data.model;

import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Clinica generated by hbm2java
 */
@Entity
@Table(name = "clinica"
)
public class Clinica implements java.io.Serializable {

    private Integer idClinica;
    private String ruc;
    private String nombreComercial;
    private String nombreAbreviado;
    private String direccionComercial;
    private String logo;
    private Integer tiempoCita;
    private Integer orden;
    private String paginaWeb;
    private String estado;
    private Integer usCreacion;
    private Date feCreacion;
    private Integer usModificacion;
    private Date feModificacion;
    private List<Administrador> administradors = new ArrayList<>();
    private List<Sede> sedes = new ArrayList<>();
    private List<Asistente> asistentes = new ArrayList<>();
    private List<Profesional> profesionals = new ArrayList<>();

    public Clinica() {
    }

    public Clinica(Integer idClinica) {
        this.idClinica = idClinica;
    }

    public Clinica(Integer idClinica, String ruc, String nombreComercial, String nombreAbreviado, String direccionComercial, String logo, String estado, Integer usCreacion, Date feCreacion, Integer usModificacion, Date feModificacion, List<Administrador> administradors, List<Sede> sedes, List<Asistente> asistentes) {
        this.idClinica = idClinica;
        this.ruc = ruc;
        this.nombreComercial = nombreComercial;
        this.nombreAbreviado = nombreAbreviado;
        this.direccionComercial = direccionComercial;
        this.logo = logo;
        this.estado = estado;
        this.usCreacion = usCreacion;
        this.feCreacion = feCreacion;
        this.usModificacion = usModificacion;
        this.feModificacion = feModificacion;
        this.administradors = administradors;
        this.sedes = sedes;
        this.asistentes = asistentes;
    }

    @Id

    @Column(name = "id_clinica", unique = true, nullable = false)
    public Integer getIdClinica() {
        return this.idClinica;
    }

    public void setIdClinica(Integer idClinica) {
        this.idClinica = idClinica;
    }

    @Column(name = "ruc", length = 11)
    public String getRuc() {
        return this.ruc;
    }

    public void setRuc(String ruc) {
        this.ruc = ruc;
    }

    @Column(name = "nombre_comercial", length = 50)
    public String getNombreComercial() {
        return this.nombreComercial;
    }

    public void setNombreComercial(String nombreComercial) {
        this.nombreComercial = nombreComercial;
    }

    @Column(name = "nombre_abreviado", length = 50)
    public String getNombreAbreviado() {
        return this.nombreAbreviado;
    }

    public void setNombreAbreviado(String nombreAbreviado) {
        this.nombreAbreviado = nombreAbreviado;
    }

    @Column(name = "direccion_comercial", length = 50)
    public String getDireccionComercial() {
        return this.direccionComercial;
    }

    public void setDireccionComercial(String direccionComercial) {
        this.direccionComercial = direccionComercial;
    }

    @Column(name = "logo", length = 50)
    public String getLogo() {
        return this.logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }

    @Column(name = "tiempo_cita")
    public Integer getTiempoCita() {
        return tiempoCita;
    }

    public void setTiempoCita(Integer tiempoCita) {
        this.tiempoCita = tiempoCita;
    }

    @Column(name = "orden")
    public Integer getOrden() {
        return orden;
    }

    public void setOrden(Integer orden) {
        this.orden = orden;
    }

    @Column(name = "pagina_web", length = 50)
    public String getPaginaWeb() {
        return paginaWeb;
    }

    public void setPaginaWeb(String paginaWeb) {
        this.paginaWeb = paginaWeb;
    }

    @Column(name = "estado", length = 1, updatable = false)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Column(name = "us_creacion", updatable = false)
    public Integer getUsCreacion() {
        return this.usCreacion;
    }

    public void setUsCreacion(Integer usCreacion) {
        this.usCreacion = usCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fe_creacion", length = 35, updatable = false)
    public Date getFeCreacion() {
        return this.feCreacion;
    }

    public void setFeCreacion(Date feCreacion) {
        this.feCreacion = feCreacion;
    }

    @Column(name = "us_modificacion")
    public Integer getUsModificacion() {
        return this.usModificacion;
    }

    public void setUsModificacion(Integer usModificacion) {
        this.usModificacion = usModificacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fe_modificacion", length = 35)
    public Date getFeModificacion() {
        return this.feModificacion;
    }

    public void setFeModificacion(Date feModificacion) {
        this.feModificacion = feModificacion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "clinica")
    public List<Administrador> getAdministradors() {
        return this.administradors;
    }

    public void setAdministradors(List<Administrador> administradors) {
        this.administradors = administradors;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "clinica")
    public List<Sede> getSedes() {
        return this.sedes;
    }

    public void setSedes(List<Sede> sedes) {
        this.sedes = sedes;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "clinica")
    public List<Asistente> getAsistentes() {
        return this.asistentes;
    }

    public void setAsistentes(List<Asistente> asistentes) {
        this.asistentes = asistentes;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "clinica")
    public List<Profesional> getProfesionals() {
        return profesionals;
    }

    public void setProfesionals(List<Profesional> profesionals) {
        this.profesionals = profesionals;
    }

    @PreUpdate
    protected void onUpdate() {
        feModificacion = new Date();
    }

}
