package com.doctorfast.cs.data.model;

import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Especialidad generated by hbm2java
 */
@Entity
@Table(name = "especialidad"
)
public class Especialidad implements java.io.Serializable {

    private Integer idEspecialidad;
    private String codigo;
    private String nombre;
    private String estado;
    private Integer usCreacion;
    private Date feCreacion;
    private Integer usModificacion;
    private Date feModificacion;
    private List<SedeEspecialidad> sedeEspecialidads = new ArrayList<>();
    private List<Subespecialidad> subespecialidads = new ArrayList<>();

    public Especialidad() {
    }

    public Especialidad(Integer idEspecialidad) {
        this.idEspecialidad = idEspecialidad;
    }

    public Especialidad(Integer idEspecialidad, String codigo, String estado, Integer usCreacion, Date feCreacion, Integer usModificacion, Date feModificacion, List<SedeEspecialidad> sedeEspecialidads, List<Subespecialidad> subespecialidads) {
        this.idEspecialidad = idEspecialidad;
        this.codigo = codigo;
        this.estado = estado;
        this.usCreacion = usCreacion;
        this.feCreacion = feCreacion;
        this.usModificacion = usModificacion;
        this.feModificacion = feModificacion;
        this.sedeEspecialidads = sedeEspecialidads;
        this.subespecialidads = subespecialidads;
    }

    @Id

    @Column(name = "id_especialidad", unique = true, nullable = false)
    public Integer getIdEspecialidad() {
        return this.idEspecialidad;
    }

    public void setIdEspecialidad(Integer idEspecialidad) {
        this.idEspecialidad = idEspecialidad;
    }

    @Column(name = "codigo", length = 50)
    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    @Column(name = "nombre", length = 50)
    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "estado", length = 1)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Column(name = "us_creacion", updatable = false)
    public Integer getUsCreacion() {
        return this.usCreacion;
    }

    public void setUsCreacion(Integer usCreacion) {
        this.usCreacion = usCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fe_creacion", length = 35, updatable = false)
    public Date getFeCreacion() {
        return this.feCreacion;
    }

    public void setFeCreacion(Date feCreacion) {
        this.feCreacion = feCreacion;
    }

    @Column(name = "us_modificacion")
    public Integer getUsModificacion() {
        return this.usModificacion;
    }

    public void setUsModificacion(Integer usModificacion) {
        this.usModificacion = usModificacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fe_modificacion", length = 35)
    public Date getFeModificacion() {
        return this.feModificacion;
    }

    public void setFeModificacion(Date feModificacion) {
        this.feModificacion = feModificacion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "especialidad")
    public List<SedeEspecialidad> getSedeEspecialidads() {
        return this.sedeEspecialidads;
    }

    public void setSedeEspecialidads(List<SedeEspecialidad> sedeEspecialidads) {
        this.sedeEspecialidads = sedeEspecialidads;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "especialidad")
    public List<Subespecialidad> getSubespecialidads() {
        return this.subespecialidads;
    }

    public void setSubespecialidads(List<Subespecialidad> subespecialidads) {
        this.subespecialidads = subespecialidads;
    }

}
