package com.doctorfast.cs.data.model;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Opcion generated by hbm2java
 */
@Entity
@Table(name = "opcion"
)
public class Opcion implements java.io.Serializable {

    private Integer idOpcion;
    private String noOpcion;
    private Integer idPadre;
    private String deUrl;
    private String estado;
    private List<Perfil> perfils = new ArrayList<>();

    public Opcion() {
    }

    public Opcion(Integer idOpcion) {
        this.idOpcion = idOpcion;
    }

    public Opcion(Integer idOpcion, String noOpcion, Integer idPadre, String deUrl, String estado, List<Perfil> perfils) {
        this.idOpcion = idOpcion;
        this.noOpcion = noOpcion;
        this.idPadre = idPadre;
        this.deUrl = deUrl;
        this.estado = estado;
        this.perfils = perfils;
    }

    @Id

    @Column(name = "id_opcion", unique = true, nullable = false)
    public Integer getIdOpcion() {
        return this.idOpcion;
    }

    public void setIdOpcion(Integer idOpcion) {
        this.idOpcion = idOpcion;
    }

    @Column(name = "no_opcion", length = 50)
    public String getNoOpcion() {
        return this.noOpcion;
    }

    public void setNoOpcion(String noOpcion) {
        this.noOpcion = noOpcion;
    }

    @Column(name = "id_padre")
    public Integer getIdPadre() {
        return this.idPadre;
    }

    public void setIdPadre(Integer idPadre) {
        this.idPadre = idPadre;
    }

    @Column(name = "de_url", length = 50)
    public String getDeUrl() {
        return this.deUrl;
    }

    public void setDeUrl(String deUrl) {
        this.deUrl = deUrl;
    }

    @Column(name = "estado", length = 1)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @ManyToMany(fetch = FetchType.LAZY, mappedBy = "opcions")
    public List<Perfil> getPerfils() {
        return this.perfils;
    }

    public void setPerfils(List<Perfil> perfils) {
        this.perfils = perfils;
    }

}
