package com.doctorfast.cs.data.model;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "perfil"
)
public class Perfil implements java.io.Serializable {

    private Integer idPerfil;
    private String noPerfil;
    private String estado;
    private List<PersonaUsuario> personaUsuarios = new ArrayList<>();
    private List<Opcion> opcions = new ArrayList<>();

    public Perfil() {
    }

    public Perfil(Integer idPerfil) {
        this.idPerfil = idPerfil;
    }

    public Perfil(Integer idPerfil, String noPerfil, String estado, List<PersonaUsuario> personaUsuarios, List<Opcion> opcions) {
        this.idPerfil = idPerfil;
        this.noPerfil = noPerfil;
        this.estado = estado;
        this.personaUsuarios = personaUsuarios;
        this.opcions = opcions;
    }

    @Id

    @Column(name = "id_perfil", unique = true, nullable = false)
    public Integer getIdPerfil() {
        return this.idPerfil;
    }

    public void setIdPerfil(Integer idPerfil) {
        this.idPerfil = idPerfil;
    }

    @Column(name = "no_perfil", length = 50)
    public String getNoPerfil() {
        return this.noPerfil;
    }

    public void setNoPerfil(String noPerfil) {
        this.noPerfil = noPerfil;
    }

    @Column(name = "estado", length = 1)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
    public List<PersonaUsuario> getPersonaUsuarios() {
        return this.personaUsuarios;
    }

    public void setPersonaUsuarios(List<PersonaUsuario> personaUsuarios) {
        this.personaUsuarios = personaUsuarios;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "perfil_opcion", joinColumns = {
        @JoinColumn(name = "id_perfil", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "id_opcion", nullable = false, updatable = false)})
    public List<Opcion> getOpcions() {
        return this.opcions;
    }

    public void setOpcions(List<Opcion> opcions) {
        this.opcions = opcions;
    }

}
