package com.doctorfast.cs.data.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Promociones generated by hbm2java
 */
@Entity
@Table(name = "promocion"
)
public class Promocion implements java.io.Serializable {

    private Integer idPromocion;
    private SedeEspecialidad sedeEspecialidad;
    private BigDecimal costo;
    private Date fechaInicio;
    private Date fechaFin;
    private Integer orden;
    private String imagen;
    private String descripcion;
    private String estado;
    private String usCreacion;
    private Date feCreacion;
    private String usModificacion;
    private Date feModificacion;
    private List<Cita> citas = new ArrayList<>();

    public Promocion() {
    }

    public Promocion(Integer idPromocion, SedeEspecialidad sedeEspecialidad) {
        this.idPromocion = idPromocion;
        this.sedeEspecialidad = sedeEspecialidad;
    }

    public Promocion(Integer idPromocion, SedeEspecialidad sedeEspecialidad, BigDecimal costo, Date fechaInicio, Date fechaFin, String estado, String usCreacion, Date feCreacion, String usModificacion, Date feModificacion, List<Cita> citas) {
        this.idPromocion = idPromocion;
        this.sedeEspecialidad = sedeEspecialidad;
        this.costo = costo;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.estado = estado;
        this.usCreacion = usCreacion;
        this.feCreacion = feCreacion;
        this.usModificacion = usModificacion;
        this.feModificacion = feModificacion;
        this.citas = citas;
    }

    @Id

    @Column(name = "id_promocion", unique = true, nullable = false)
    public Integer getIdPromocion() {
        return this.idPromocion;
    }

    public void setIdPromocion(Integer idPromocion) {
        this.idPromocion = idPromocion;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumns({
        @JoinColumn(name = "id_sede", referencedColumnName = "id_sede", nullable = false),
        @JoinColumn(name = "id_especialidad", referencedColumnName = "id_especialidad", nullable = false)})
    public SedeEspecialidad getSedeEspecialidad() {
        return this.sedeEspecialidad;
    }

    public void setSedeEspecialidad(SedeEspecialidad sedeEspecialidad) {
        this.sedeEspecialidad = sedeEspecialidad;
    }

    @Column(name = "costo", precision = 131089, scale = 0)
    public BigDecimal getCosto() {
        return this.costo;
    }

    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_inicio", length = 35)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fecha_fin", length = 35)
    public Date getFechaFin() {
        return this.fechaFin;
    }

    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    @Column(name = "orden")
    public Integer getOrden() {
        return orden;
    }

    public void setOrden(Integer orden) {
        this.orden = orden;
    }

    @Column(name = "imagen", length = 50)
    public String getImagen() {
        return imagen;
    }

    public void setImagen(String imagen) {
        this.imagen = imagen;
    }

    @Column(name = "descripcion", length = 200)
    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "estado", length = 1)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Column(name = "us_creacion", updatable = false, length = 50)
    public String getUsCreacion() {
        return this.usCreacion;
    }

    public void setUsCreacion(String usCreacion) {
        this.usCreacion = usCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fe_creacion", length = 35, updatable = false)
    public Date getFeCreacion() {
        return this.feCreacion;
    }

    public void setFeCreacion(Date feCreacion) {
        this.feCreacion = feCreacion;
    }

    @Column(name = "us_modificacion", length = 50)
    public String getUsModificacion() {
        return this.usModificacion;
    }

    public void setUsModificacion(String usModificacion) {
        this.usModificacion = usModificacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fe_modificacion", length = 35)
    public Date getFeModificacion() {
        return this.feModificacion;
    }

    public void setFeModificacion(Date feModificacion) {
        this.feModificacion = feModificacion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "promocion")
    public List<Cita> getCitas() {
        return this.citas;
    }

    public void setCitas(List<Cita> citas) {
        this.citas = citas;
    }

}
