package com.doctorfast.cs.data.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SedeEspSubespId generated by hbm2java
 */
@Embeddable
public class SedeEspSubespId implements java.io.Serializable {

    private Integer idSede;
    private Integer idEspecialidad;
    private Integer idSubespecialidad;

    public SedeEspSubespId() {
    }

    public SedeEspSubespId(Integer idSede, int idEspecialidad, int idSubespecialidad) {
        this.idSede = idSede;
        this.idEspecialidad = idEspecialidad;
        this.idSubespecialidad = idSubespecialidad;
    }

    @Column(name = "id_sede", nullable = false)
    public Integer getIdSede() {
        return this.idSede;
    }

    public void setIdSede(Integer idSede) {
        this.idSede = idSede;
    }

    @Column(name = "id_especialidad", nullable = false)
    public Integer getIdEspecialidad() {
        return this.idEspecialidad;
    }

    public void setIdEspecialidad(Integer idEspecialidad) {
        this.idEspecialidad = idEspecialidad;
    }

    @Column(name = "id_subespecialidad", nullable = false)
    public Integer getIdSubespecialidad() {
        return this.idSubespecialidad;
    }

    public void setIdSubespecialidad(Integer idSubespecialidad) {
        this.idSubespecialidad = idSubespecialidad;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof SedeEspSubespId)) {
            return false;
        }
        SedeEspSubespId castOther = (SedeEspSubespId) other;

        return (this.getIdSede() == castOther.getIdSede())
                && (this.getIdEspecialidad() == castOther.getIdEspecialidad())
                && (this.getIdSubespecialidad() == castOther.getIdSubespecialidad());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getIdSede();
        result = 37 * result + this.getIdEspecialidad();
        result = 37 * result + this.getIdSubespecialidad();
        return result;
    }

}
