package com.doctorfast.cs.data.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SedeEspecialidadId generated by hbm2java
 */
@Embeddable
public class SedeEspecialidadId implements java.io.Serializable {

    private Integer idEspecialidad;
    private Integer idSede;

    public SedeEspecialidadId() {
    }

    public SedeEspecialidadId(Integer idEspecialidad, int idSede) {
        this.idEspecialidad = idEspecialidad;
        this.idSede = idSede;
    }

    @Column(name = "id_especialidad", nullable = false)
    public Integer getIdEspecialidad() {
        return this.idEspecialidad;
    }

    public void setIdEspecialidad(Integer idEspecialidad) {
        this.idEspecialidad = idEspecialidad;
    }

    @Column(name = "id_sede", nullable = false)
    public Integer getIdSede() {
        return this.idSede;
    }

    public void setIdSede(Integer idSede) {
        this.idSede = idSede;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof SedeEspecialidadId)) {
            return false;
        }
        SedeEspecialidadId castOther = (SedeEspecialidadId) other;

        return (this.getIdEspecialidad() == castOther.getIdEspecialidad())
                && (this.getIdSede() == castOther.getIdSede());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getIdEspecialidad();
        result = 37 * result + this.getIdSede();
        return result;
    }

}
