package com.doctorfast.cs.data.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SedeEspecialidad generated by hbm2java
 */
@Entity
@Table(name = "sede_especialidad"
)
public class SedeEspecialidad implements java.io.Serializable {

    private SedeEspecialidadId id;
    private Especialidad especialidad;
    private Sede sede;
    private BigDecimal costoConsulta;
    private BigDecimal costo;
    private String estado;
    private List<Promocion> promociones = new ArrayList<>();
    private List<SedeEspSubesp> sedeEspSubesps = new ArrayList<>();

    public SedeEspecialidad() {
    }

    public SedeEspecialidad(SedeEspecialidadId id, Especialidad especialidad, Sede sede) {
        this.id = id;
        this.especialidad = especialidad;
        this.sede = sede;
    }

    @EmbeddedId
    @AttributeOverrides({
        @AttributeOverride(name = "idEspecialidad", column = @Column(name = "id_especialidad", nullable = false)),
        @AttributeOverride(name = "idSede", column = @Column(name = "id_sede", nullable = false))})
    public SedeEspecialidadId getId() {
        return this.id;
    }

    public void setId(SedeEspecialidadId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "id_especialidad", nullable = false, insertable = false, updatable = false)
    public Especialidad getEspecialidad() {
        return this.especialidad;
    }

    public void setEspecialidad(Especialidad especialidad) {
        this.especialidad = especialidad;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "id_sede", nullable = false, insertable = false, updatable = false)
    public Sede getSede() {
        return this.sede;
    }

    public void setSede(Sede sede) {
        this.sede = sede;
    }

    @Column(name = "costo_consulta", precision = 131089, scale = 0)
    public BigDecimal getCostoConsulta() {
        return this.costoConsulta;
    }

    public void setCostoConsulta(BigDecimal costoConsulta) {
        this.costoConsulta = costoConsulta;
    }

    @Column(name = "costo", precision = 131089, scale = 0)
    public BigDecimal getCosto() {
        return this.costo;
    }

    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }

    @Column(name = "estado", length = 1)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sedeEspecialidad")
    public List<Promocion> getPromociones() {
        return this.promociones;
    }

    public void setPromociones(List<Promocion> promociones) {
        this.promociones = promociones;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "sedeEspecialidad")
    public List<SedeEspSubesp> getSedeEspSubesps() {
        return this.sedeEspSubesps;
    }

    public void setSedeEspSubesps(List<SedeEspSubesp> sedeEspSubesps) {
        this.sedeEspSubesps = sedeEspSubesps;
    }

}
