package com.doctorfast.cs.data.model;

import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Subespecialidad generated by hbm2java
 */
@Entity
@Table(name = "subespecialidad"
)
public class Subespecialidad implements java.io.Serializable {

    private Integer idSubespecialidad;
    private Especialidad especialidad;
    private String nombre;
    private String estado;
    private Integer usCreacion;
    private Date feCreacion;
    private Integer usModificacion;
    private Date feModificacion;
    private List<SedeEspSubesp> sedeEspSubesps = new ArrayList<>();
    private List<Cita> citas = new ArrayList<>();

    public Subespecialidad() {
    }

    public Subespecialidad(Integer idSubespecialidad, Especialidad especialidad) {
        this.idSubespecialidad = idSubespecialidad;
        this.especialidad = especialidad;
    }

    public Subespecialidad(Integer idSubespecialidad, Especialidad especialidad, String estado, Integer usCreacion, Date feCreacion, Integer usModificacion, Date feModificacion, List<SedeEspSubesp> sedeEspSubesps) {
        this.idSubespecialidad = idSubespecialidad;
        this.especialidad = especialidad;
        this.estado = estado;
        this.usCreacion = usCreacion;
        this.feCreacion = feCreacion;
        this.usModificacion = usModificacion;
        this.feModificacion = feModificacion;
        this.sedeEspSubesps = sedeEspSubesps;
    }

    @Id

    @Column(name = "id_subespecialidad", unique = true, nullable = false)
    public Integer getIdSubespecialidad() {
        return this.idSubespecialidad;
    }

    public void setIdSubespecialidad(Integer idSubespecialidad) {
        this.idSubespecialidad = idSubespecialidad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_especialidad", nullable = false)
    public Especialidad getEspecialidad() {
        return this.especialidad;
    }

    public void setEspecialidad(Especialidad especialidad) {
        this.especialidad = especialidad;
    }

    @Column(name = "nombre", length = 50)
    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "estado", length = 1)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    @Column(name = "us_creacion", updatable = false)
    public Integer getUsCreacion() {
        return this.usCreacion;
    }

    public void setUsCreacion(Integer usCreacion) {
        this.usCreacion = usCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fe_creacion", length = 35, updatable = false)
    public Date getFeCreacion() {
        return this.feCreacion;
    }

    public void setFeCreacion(Date feCreacion) {
        this.feCreacion = feCreacion;
    }

    @Column(name = "us_modificacion")
    public Integer getUsModificacion() {
        return this.usModificacion;
    }

    public void setUsModificacion(Integer usModificacion) {
        this.usModificacion = usModificacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "fe_modificacion", length = 35)
    public Date getFeModificacion() {
        return this.feModificacion;
    }

    public void setFeModificacion(Date feModificacion) {
        this.feModificacion = feModificacion;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "subespecialidad")
    public List<SedeEspSubesp> getSedeEspSubesps() {
        return this.sedeEspSubesps;
    }

    public void setSedeEspSubesps(List<SedeEspSubesp> sedeEspSubesps) {
        this.sedeEspSubesps = sedeEspSubesps;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "subespecialidad")
    public List<Cita> getCitas() {
        return this.citas;
    }

    public void setCitas(List<Cita> citas) {
        this.citas = citas;
    }

}
