package com.doctorfast.cs.data.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Ubigeo generated by hbm2java
 */
@Entity
@Table(name = "ubigeo"
)
public class Ubigeo implements java.io.Serializable {

    private UbigeoId id;
    private String noDepartamento;
    private String noProvincia;
    private String noDistrito;
    private String estado;

    public Ubigeo() {
    }

    public Ubigeo(UbigeoId id) {
        this.id = id;
    }

    public Ubigeo(UbigeoId id, String noDepartamento, String noProvincia, String noDistrito, String estado) {
        this.id = id;
        this.noDepartamento = noDepartamento;
        this.noProvincia = noProvincia;
        this.noDistrito = noDistrito;
        this.estado = estado;
    }

    @EmbeddedId

    @AttributeOverrides({
        @AttributeOverride(name = "coDepartamento", column = @Column(name = "co_departamento", nullable = false)),
        @AttributeOverride(name = "coProvincia", column = @Column(name = "co_provincia", nullable = false)),
        @AttributeOverride(name = "coDistrito", column = @Column(name = "co_distrito", nullable = false))})
    public UbigeoId getId() {
        return this.id;
    }

    public void setId(UbigeoId id) {
        this.id = id;
    }

    @Column(name = "no_departamento", length = 50)
    public String getNoDepartamento() {
        return this.noDepartamento;
    }

    public void setNoDepartamento(String noDepartamento) {
        this.noDepartamento = noDepartamento;
    }

    @Column(name = "no_provincia", length = 50)
    public String getNoProvincia() {
        return this.noProvincia;
    }

    public void setNoProvincia(String noProvincia) {
        this.noProvincia = noProvincia;
    }

    @Column(name = "no_distrito")
    public String getNoDistrito() {
        return this.noDistrito;
    }

    public void setNoDistrito(String noDistrito) {
        this.noDistrito = noDistrito;
    }

    @Column(name = "estado", length = 1)
    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

}
